### ISSUE TITLE
What's the goal of collaboration here?

### ISSUE THREAD

**Issue by chmac** [TripSit/comboapp#11]
I'd like to get a bit of a sense of what you're hoping for from me here.

Just a little back story. I wrote this app because I found that the table was great data, but impractical while in a state of insobriety, and only supported two substance interactions. Both of which seemed a little less than useful to me. Then some folks at TripSit took it over, made some UI changes to maybe better match the other parts of the site or something. Then it crashed a bunch, it was routinely offline, there was no maintenance, and nobody answered any of my questions about how to straighten it out. I offered to take care of the hosting altogether, it's just a static site, but that also was never addressed.

In #8 I see that you're practicing some kind of security policy, which I guess puts you on the inside, and me on the outside. Fair enough, that's your prerogative. But it leads me to wonder, what is it you would like from me here? How do you see this working? What's the volunteer culture like at TripSit?

**Comment by LunaUrsa** [comment]
That helps, thank you, I am unfamiliar with that history, and I appreciate that you got this ball rolling. I can understand your disappointment with the lack of response from the team; it was not intentional, there have been many internal changes over the past few years, and we have not been super organized in the past. 

For my backstory: I was only involved in the development aspects of tripsit about two years ago, and I am not a professional developer, just passionate and learning everything as I go. As you can tell, there is not much of a developer team here; Bjorn has not been part of the team for multiple years. It's me trying to figure out what to do with our code and everything else going on with tripsit with some part-time help from other developers. We have an open-door policy if anyone has questions or wants to get involved; our development discussions on Discord are public to those who want to help out. 

I'm open to anything you want to contribute and to ideas on how you want to collaborate. I mentioned I'm not a professional developer, so I'm not completely sure how to best collaborate on Git Hub, I just didn't want to give full permissions to someone I've just met. Anything is possible really, I'm the only one who needs to approve any development actions. I'd say more of a question of how much you want to contribute and how you want to do that?

**Comment by chmac** [comment]
I hear that you're reluctant to give permissions to somebody you just met. I'm just not sure what you want me to do in that case. I can't merge changes, I can't deploy stuff. So I guess you need to do all that stuff. But I also hear that you're learning as you go. So I guess that leaves us with you figuring this stuff out and me watching. :-)

**Comment by LunaUrsa** [comment]
I appreciate your patience, I updated your permissions, you should have all the permissions you need, and if you need admin perms, we can discuss them. I'm not trying to exclude you or make any "inside vs outside" collaboration; just not sure the best way to do this, but I want to make this happen, so I'm open to trying things
